package vistas;

import Controloador.UserHistoryController;
import classes.Department;
import classes.Town;
import classes.Township;
import classes.User;
import dao.UserDao;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class IfrmSystem extends javax.swing.JInternalFrame {
int blo=0;
UserDao usdao = new UserDao();
DefaultTableModel dtmUser;
    /**
     * Creates new form frmUser
     */
    public IfrmSystem() {
        initComponents();
        UserHistoryController sserHistoryController = new UserHistoryController(this);
        //this.tpnControl.setEnabled(false);
        this.btnNewUser.setEnabled(false);
        this.lstDepartments.setEnabled(false);
        this.lstTownships.setEnabled(false);
        this.lstTown.setEnabled(false);
        this.tblUserHistory.setEnabled(false);
        this.tblUser.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    mnuOpition = new javax.swing.JPopupMenu();
    mniModi = new javax.swing.JMenuItem();
    mnuState = new javax.swing.JMenu();
    mniDel = new javax.swing.JMenuItem();
    mniActi = new javax.swing.JMenuItem();
    btnDesbloquear = new javax.swing.JButton();
    tpnControl = new javax.swing.JTabbedPane();
    panUser = new javax.swing.JPanel();
    btnNewUser = new javax.swing.JButton();
    jScrollPane6 = new javax.swing.JScrollPane();
    tblUser = new javax.swing.JTable();
    panTowns = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    lstTown = new javax.swing.JList<>();
    lblDep = new javax.swing.JLabel();
    jScrollPane4 = new javax.swing.JScrollPane();
    lstDepartments = new javax.swing.JList<>();
    jScrollPane5 = new javax.swing.JScrollPane();
    lstTownships = new javax.swing.JList<>();
    lblTowns = new javax.swing.JLabel();
    lblMuni = new javax.swing.JLabel();
    panRegistro = new javax.swing.JPanel();
    jScrollPane3 = new javax.swing.JScrollPane();
    tblUserHistory = new javax.swing.JTable();
    txtDayHistory = new javax.swing.JTextField();
    txtMonthHistory = new javax.swing.JTextField();
    txtYearHistory = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    cmbUsersHistory = new javax.swing.JComboBox<>();
    jLabel4 = new javax.swing.JLabel();
    btnFetchHistory = new javax.swing.JButton();
    btnOpenDeleteUserHistory = new javax.swing.JButton();
    btnCanselar = new javax.swing.JButton();

    mnuOpition.setToolTipText("");

    mniModi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/user-business-info-icon.png"))); // NOI18N
    mniModi.setText("Modificar");
    mniModi.setToolTipText("Modifica la información del usuario");
    mniModi.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mniModiActionPerformed(evt);
      }
    });
    mnuOpition.add(mniModi);

    mnuState.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/user-business-info-icon.png"))); // NOI18N
    mnuState.setText("estados del Usuario");
    mnuState.setToolTipText("opciones de estado");

    mniDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/status_offline.png"))); // NOI18N
    mniDel.setText("Inactivo");
    mniDel.setToolTipText("canbia el estado del servisio a Inactivo");
    mniDel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mniDelActionPerformed(evt);
      }
    });
    mnuState.add(mniDel);

    mniActi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/status_online.png"))); // NOI18N
    mniActi.setText("Activar");
    mniActi.setToolTipText("Canbia el estatus del servisio a activo");
    mnuState.add(mniActi);

    mnuOpition.add(mnuState);

    setBorder(javax.swing.BorderFactory.createTitledBorder(""));
    setIconifiable(true);
    setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/ajustes (2).png"))); // NOI18N

    btnDesbloquear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/Lock-icon.png"))); // NOI18N
    btnDesbloquear.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDesbloquearActionPerformed(evt);
      }
    });

    btnNewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/user-business-add-icon.png"))); // NOI18N
    btnNewUser.setToolTipText("Guardar");
    btnNewUser.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNewUserActionPerformed(evt);
      }
    });

    tblUser.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Npmbre de Usuario", "tipo de usuario", "estado"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.Integer.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    tblUser.setComponentPopupMenu(mnuOpition);
    tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        tblUserMousePressed(evt);
      }
    });
    jScrollPane6.setViewportView(tblUser);

    javax.swing.GroupLayout panUserLayout = new javax.swing.GroupLayout(panUser);
    panUser.setLayout(panUserLayout);
    panUserLayout.setHorizontalGroup(
      panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUserLayout.createSequentialGroup()
        .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(panUserLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(20, 20, 20))
          .addGroup(panUserLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)))
        .addContainerGap())
    );
    panUserLayout.setVerticalGroup(
      panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUserLayout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addComponent(btnNewUser)
        .addGap(36, 36, 36))
    );

    tpnControl.addTab("Usuarios", panUser);

    jScrollPane2.setViewportView(lstTown);

    lblDep.setFont(new java.awt.Font("Purisa", 1, 10)); // NOI18N
    lblDep.setText("Departamentos");

    jScrollPane4.setViewportView(lstDepartments);

    jScrollPane5.setViewportView(lstTownships);

    lblTowns.setFont(new java.awt.Font("Purisa", 1, 10)); // NOI18N
    lblTowns.setText("colonias y condominios");

    lblMuni.setFont(new java.awt.Font("Purisa", 1, 10)); // NOI18N
    lblMuni.setText("Municipios");

    javax.swing.GroupLayout panTownsLayout = new javax.swing.GroupLayout(panTowns);
    panTowns.setLayout(panTownsLayout);
    panTownsLayout.setHorizontalGroup(
      panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panTownsLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panTownsLayout.createSequentialGroup()
            .addGroup(panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panTownsLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblMuni))
              .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(38, 38, 38))
          .addGroup(panTownsLayout.createSequentialGroup()
            .addComponent(lblDep)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTowns)
            .addGap(95, 95, 95))))
    );
    panTownsLayout.setVerticalGroup(
      panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panTownsLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblDep, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblTowns, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(6, 6, 6)
        .addGroup(panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(panTownsLayout.createSequentialGroup()
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblMuni, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jScrollPane2))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    tpnControl.addTab("Colonias", panTowns);

    tblUserHistory.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Usuario", "Fecha", "Hora", "URL"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane3.setViewportView(tblUserHistory);

    txtDayHistory.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txtDayHistory.setText("20");

    txtMonthHistory.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txtMonthHistory.setText("12");

    txtYearHistory.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txtYearHistory.setText("2017");

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("/");

    jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("/");

    jLabel3.setText("Fecha: ");

    jLabel4.setText("Usuario: ");

    btnFetchHistory.setText("Buscar");

    btnOpenDeleteUserHistory.setText("Borrar Historial");

    javax.swing.GroupLayout panRegistroLayout = new javax.swing.GroupLayout(panRegistro);
    panRegistro.setLayout(panRegistroLayout);
    panRegistroLayout.setHorizontalGroup(
      panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panRegistroLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
          .addGroup(panRegistroLayout.createSequentialGroup()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cmbUsersHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtDayHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(4, 4, 4)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(4, 4, 4)
            .addComponent(txtMonthHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(4, 4, 4)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(3, 3, 3)
            .addComponent(txtYearHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnFetchHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRegistroLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnOpenDeleteUserHistory)
        .addGap(257, 257, 257))
    );
    panRegistroLayout.setVerticalGroup(
      panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRegistroLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(cmbUsersHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3)
          .addComponent(txtDayHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1)
          .addComponent(txtMonthHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2)
          .addComponent(txtYearHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnFetchHistory))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnOpenDeleteUserHistory)
        .addContainerGap())
    );

    tpnControl.addTab("Registros", panRegistro);

    btnCanselar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/Delete-icon.png"))); // NOI18N
    btnCanselar.setToolTipText("Cerrar");
    btnCanselar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCanselarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(tpnControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnDesbloquear, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCanselar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(19, 19, 19))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(tpnControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnDesbloquear)
          .addComponent(btnCanselar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    getAccessibleContext().setAccessibleParent(this);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnDesbloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesbloquearActionPerformed
  
        String pass = "Leo";
        if (blo==0){
        JFrame frame = new JFrame("InputDialog Example");
        String code = JOptionPane.showInputDialog(frame, " Ingrese el codigo para la confirmaion de desbloqueo",
                "confirmacion", JOptionPane.WARNING_MESSAGE);
            if (code == null) {
                JOptionPane.showMessageDialog(null, "Has canselado.");
            } else if (code.equals(pass)) {
                int ax = JOptionPane.showConfirmDialog(null, "Estas seguro?", "Desbloqueo", JOptionPane.OK_CANCEL_OPTION);
                if (ax == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(null, "Has desbloqueado.");
                    //this.tpnControl.setEnabled(true);
                    this.btnNewUser.setEnabled(true);
                    this.lstDepartments.setEnabled(true);
                    this.lstTownships.setEnabled(true);
                    this.lstTown.setEnabled(true);
                    this.tblUserHistory.setEnabled(true);
                    this.tblUser.setEnabled(true);
                    dtmUser = (DefaultTableModel)tblUser.getModel();
                    Object[] columna = new Object[dtmUser.getColumnCount()];
                    ArrayList<User> usuarios =  usdao.displayUser();
                    tblUser.removeAll();
                    int tam = usuarios.size();
                    for(int i = 0; i < tam; i++){
                        columna[0] = usuarios.get(i).getUsername();
                        columna[1] = usuarios.get(i).getUserType();
                        dtmUser.addRow(columna);
                    }
                    blo = 1;
                    ImageIcon icono2 = new ImageIcon(System.getProperty("user.dir") + "/build/classes/resources/Icons/Unlock-icon.png");
                    this.btnDesbloquear.setIcon(icono2);
                } else if (ax == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                }
            }
        }else if (blo == 1){

            this.btnNewUser.setEnabled(false);
            this.lstDepartments.setEnabled(false);
            this.lstTownships.setEnabled(false);
            this.lstTown.setEnabled(false);
            this.tblUserHistory.setEnabled(false);
            this.tblUser.setEnabled(false);

            ImageIcon icono3 = new ImageIcon(System.getProperty("user.dir") + "/build/classes/resources/Icons/Lock-icon.png");
            this.btnDesbloquear.setIcon(icono3);
            blo = 0;
        }    
    }//GEN-LAST:event_btnDesbloquearActionPerformed
    private void btnCanselarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanselarActionPerformed
        try {
            // TODO add your handling code here:
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(IfrmSystem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCanselarActionPerformed

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserActionPerformed
        //TODO add your handling code here:
    }//GEN-LAST:event_btnNewUserActionPerformed

    private void tblUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMousePressed
        // TODO add your handling code here:
       // Integer filaSelec = tblUser.getSelectedRow();
        //Object[] options = null;
        
    }//GEN-LAST:event_tblUserMousePressed

    private void mniDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDelActionPerformed

    private void mniModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniModiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniModiActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCanselar;
  public javax.swing.JButton btnDesbloquear;
  public javax.swing.JButton btnFetchHistory;
  public javax.swing.JButton btnNewUser;
  public javax.swing.JButton btnOpenDeleteUserHistory;
  public javax.swing.JComboBox<User> cmbUsersHistory;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JScrollPane jScrollPane5;
  private javax.swing.JScrollPane jScrollPane6;
  private javax.swing.JLabel lblDep;
  private javax.swing.JLabel lblMuni;
  private javax.swing.JLabel lblTowns;
  public javax.swing.JList<Department> lstDepartments;
  public javax.swing.JList<Town> lstTown;
  public javax.swing.JList<Township> lstTownships;
  public javax.swing.JMenuItem mniActi;
  private javax.swing.JMenuItem mniDel;
  public javax.swing.JMenuItem mniModi;
  private javax.swing.JPopupMenu mnuOpition;
  public javax.swing.JMenu mnuState;
  private javax.swing.JPanel panRegistro;
  private javax.swing.JPanel panTowns;
  public javax.swing.JPanel panUser;
  public javax.swing.JTable tblUser;
  public javax.swing.JTable tblUserHistory;
  public javax.swing.JTabbedPane tpnControl;
  public javax.swing.JTextField txtDayHistory;
  public javax.swing.JTextField txtMonthHistory;
  public javax.swing.JTextField txtYearHistory;
  // End of variables declaration//GEN-END:variables
}
