package vistas;

import Controloador.ControlUser;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author medev
 */
public class IfrmSystem extends javax.swing.JInternalFrame {
int blo=0;
    /**
     * Creates new form frmUser
     */
    public IfrmSystem() {
        initComponents();
        //this.tpnControl.setEnabled(false);
        this.pwdPass.setEnabled(false);
        this.btnSaveCol.setEnabled(false);
        this.btnSaveUser.setEnabled(false);
        this.btnAddTowns.setEnabled(false);
        this.btnDeleteTowns.setEnabled(false);
        this.btnSearchTowns.setEnabled(false);
        this.cmbTypeUser.setEnabled(false);
        this.lstUser.setEnabled(false);
        this.lstDepartments.setEnabled(false);
        this.lstTownships.setEnabled(false);
        this.lstTown.setEnabled(false);
        this.lblUser.setEnabled(false);
        this.lblTypeUser.setEnabled(false);
        this.lblPass.setEnabled(false);
        this.txtUser.setEnabled(false);
        this.tblHistory.setEnabled(false);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDesbloquear = new javax.swing.JButton();
        tpnControl = new javax.swing.JTabbedPane();
        panUser = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUser = new javax.swing.JList<>();
        txtUser = new javax.swing.JTextField();
        pwdPass = new javax.swing.JPasswordField();
        lblTypeUser = new javax.swing.JLabel();
        cmbTypeUser = new javax.swing.JComboBox<>();
        panTowns = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTown = new javax.swing.JList<>();
        btnSaveCol = new javax.swing.JButton();
        btnDeleteTowns = new javax.swing.JButton();
        btnAddTowns = new javax.swing.JButton();
        btnSearchTowns = new javax.swing.JButton();
        lblDep = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstDepartments = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstTownships = new javax.swing.JList<>();
        lblTowns = new javax.swing.JLabel();
        lblMuni = new javax.swing.JLabel();
        panRegistro = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setIconifiable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/ajustes (2).png"))); // NOI18N

        btnDesbloquear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/Lock-icon.png"))); // NOI18N
        btnDesbloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesbloquearActionPerformed(evt);
            }
        });

        btnSaveUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/Check-icon.png"))); // NOI18N
        btnSaveUser.setToolTipText("Guardar");

        lblUser.setText("Usuario");

        lblPass.setText("Contraseña");

        lstUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstUser.setToolTipText("Lista de usuarisos del sistema");
        jScrollPane1.setViewportView(lstUser);

        txtUser.setToolTipText("Nonbre del Usuario del sistemal");

        pwdPass.setToolTipText("Contraseña del Usuario del sistema");

        lblTypeUser.setText("Tipo de Usuario");

        cmbTypeUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panUserLayout = new javax.swing.GroupLayout(panUser);
        panUser.setLayout(panUserLayout);
        panUserLayout.setHorizontalGroup(
            panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUserLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panUserLayout.createSequentialGroup()
                        .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser)
                            .addComponent(lblPass))
                        .addGap(18, 18, 18)
                        .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdPass)
                            .addComponent(txtUser)))
                    .addGroup(panUserLayout.createSequentialGroup()
                        .addComponent(lblTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(cmbTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUserLayout.createSequentialGroup()
                .addContainerGap(485, Short.MAX_VALUE)
                .addComponent(btnSaveUser)
                .addContainerGap())
        );
        panUserLayout.setVerticalGroup(
            panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panUserLayout.createSequentialGroup()
                        .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUser)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPass)
                            .addComponent(pwdPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTypeUser)
                            .addComponent(cmbTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btnSaveUser)
                .addContainerGap())
        );

        tpnControl.addTab("Usuarios", panUser);

        lstTown.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstTown);

        btnSaveCol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/Check-icon.png"))); // NOI18N
        btnSaveCol.setToolTipText("Guardar");

        btnDeleteTowns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/building-delete-icon.png"))); // NOI18N
        btnDeleteTowns.setToolTipText("eliminar una colonia o condomino");

        btnAddTowns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/building-add-icon.png"))); // NOI18N
        btnAddTowns.setToolTipText("Agregar una colonia o condomino");

        btnSearchTowns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/Search-icon.png"))); // NOI18N
        btnSearchTowns.setToolTipText("buscar una colonia");

        lblDep.setFont(new java.awt.Font("Purisa", 1, 10)); // NOI18N
        lblDep.setText("Departamentos");

        lstDepartments.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(lstDepartments);

        lstTownships.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(lstTownships);

        lblTowns.setFont(new java.awt.Font("Purisa", 1, 10)); // NOI18N
        lblTowns.setText("colonias y condominios");

        lblMuni.setFont(new java.awt.Font("Purisa", 1, 10)); // NOI18N
        lblMuni.setText("Municipios");

        javax.swing.GroupLayout panTownsLayout = new javax.swing.GroupLayout(panTowns);
        panTowns.setLayout(panTownsLayout);
        panTownsLayout.setHorizontalGroup(
            panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTownsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panTownsLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panTownsLayout.createSequentialGroup()
                        .addComponent(lblDep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMuni)
                        .addGap(73, 73, 73)))
                .addGroup(panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTowns)
                    .addGroup(panTownsLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddTowns)
                            .addComponent(btnDeleteTowns)
                            .addComponent(btnSearchTowns))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTownsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaveCol)
                .addContainerGap())
        );
        panTownsLayout.setVerticalGroup(
            panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTownsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTowns, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMuni, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panTownsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAddTowns)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteTowns)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchTowns)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(btnSaveCol)
                .addContainerGap())
        );

        tpnControl.addTab("Colonias", panTowns);

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User", "Fecha", "Paginas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblHistory);

        javax.swing.GroupLayout panRegistroLayout = new javax.swing.GroupLayout(panRegistro);
        panRegistro.setLayout(panRegistroLayout);
        panRegistroLayout.setHorizontalGroup(
            panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );
        panRegistroLayout.setVerticalGroup(
            panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        tpnControl.addTab("Registros", panRegistro);

        btnCanselar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/Delete-icon.png"))); // NOI18N
        btnCanselar.setToolTipText("Cerrar");
        btnCanselar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanselarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tpnControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDesbloquear, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCanselar)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpnControl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDesbloquear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCanselar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesbloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesbloquearActionPerformed
        System.out.println("llego al boton");
        String pass = "Leo";
        if (blo==0){
        JFrame frame = new JFrame("InputDialog Example");
        String code = JOptionPane.showInputDialog(frame, " Ingrese el codigo para la confirmaion de desbloqueo",
                "confirmacion", JOptionPane.WARNING_MESSAGE);
        System.out.println(code);
            if (code == null) {
                JOptionPane.showMessageDialog(null, "Has canselado.");
            } else if (code.equals(pass)) {
                int ax = JOptionPane.showConfirmDialog(null, "Estas seguro?", "Desbloqueo", JOptionPane.OK_CANCEL_OPTION);
                if (ax == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(null, "Has desbloqueado.");
                    //this.tpnControl.setEnabled(true);
                    this.pwdPass.setEnabled(true);
                    this.btnSaveCol.setEnabled(true);
                    this.btnSaveUser.setEnabled(true);
                    this.btnAddTowns.setEnabled(true);
                    this.btnDeleteTowns.setEnabled(true);
                    this.btnSearchTowns.setEnabled(true);
                    this.cmbTypeUser.setEnabled(true);
                    this.lstUser.setEnabled(true);
                    this.lstDepartments.setEnabled(true);
                    this.lstTownships.setEnabled(true);
                    this.lstTown.setEnabled(true);
                    this.lblUser.setEnabled(true);
                    this.lblTypeUser.setEnabled(true);
                    this.lblPass.setEnabled(true);
                    this.txtUser.setEnabled(true);
                    this.tblHistory.setEnabled(true);
                    blo = 1;
                    ImageIcon icono2 = new ImageIcon(System.getProperty("user.dir") + "/build/classes/resources/Icons/Unlock-icon.png");
                    this.btnDesbloquear.setIcon(icono2);
                } else if (ax == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(null, "Has seleccionado NO.");
                }
            }
        }else if (blo == 1){
            this.pwdPass.setEnabled(false);
            this.btnSaveCol.setEnabled(false);
            this.btnSaveUser.setEnabled(false);
            this.btnAddTowns.setEnabled(false);
            this.btnDeleteTowns.setEnabled(false);
            this.btnSearchTowns.setEnabled(false);
            this.cmbTypeUser.setEnabled(false);
            this.lstUser.setEnabled(false);
            this.lstDepartments.setEnabled(false);
            this.lstTownships.setEnabled(false);
            this.lstTown.setEnabled(false);
            this.lblUser.setEnabled(false);
            this.lblTypeUser.setEnabled(false);
            this.lblPass.setEnabled(false);
            this.txtUser.setEnabled(false);
            this.tblHistory.setEnabled(false);

            ImageIcon icono3 = new ImageIcon(System.getProperty("user.dir") + "/build/classes/resources/Icons/Lock-icon.png");
            this.btnDesbloquear.setIcon(icono3);
            blo = 0;
        }    
    }//GEN-LAST:event_btnDesbloquearActionPerformed
    private void btnCanselarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanselarActionPerformed
        try {
            // TODO add your handling code here:
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(IfrmSystem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCanselarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddTowns;
    private static final javax.swing.JButton btnCanselar = new javax.swing.JButton();
    public javax.swing.JButton btnDeleteTowns;
    public static javax.swing.JButton btnDesbloquear;
    public javax.swing.JButton btnSaveCol;
    public static final javax.swing.JButton btnSaveUser = new javax.swing.JButton();
    public javax.swing.JButton btnSearchTowns;
    public javax.swing.JComboBox<String> cmbTypeUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblDep;
    private javax.swing.JLabel lblMuni;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTowns;
    private javax.swing.JLabel lblTypeUser;
    private javax.swing.JLabel lblUser;
    public javax.swing.JList<String> lstDepartments;
    public javax.swing.JList<String> lstTown;
    public javax.swing.JList<String> lstTownships;
    public static javax.swing.JList<String> lstUser;
    private javax.swing.JPanel panRegistro;
    private javax.swing.JPanel panTowns;
    private javax.swing.JPanel panUser;
    public javax.swing.JPasswordField pwdPass;
    public javax.swing.JTable tblHistory;
    public javax.swing.JTabbedPane tpnControl;
    public javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
