/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author javam
 */
public class IfrmPayments extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmPayments
     */
    public IfrmPayments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgMonths = new javax.swing.ButtonGroup();
        tpnControl = new javax.swing.JTabbedPane();
        panUser = new javax.swing.JPanel();
        btnSaveUser = new javax.swing.JButton();
        lblColonia1 = new javax.swing.JLabel();
        txtColonia1 = new javax.swing.JTextField();
        jrbEnero = new javax.swing.JRadioButton();
        jrbFebreo = new javax.swing.JRadioButton();
        jrbMarzo = new javax.swing.JRadioButton();
        jrbAbril = new javax.swing.JRadioButton();
        jrbMayo = new javax.swing.JRadioButton();
        jrbJunio = new javax.swing.JRadioButton();
        jrbJulio = new javax.swing.JRadioButton();
        jrbAgosto = new javax.swing.JRadioButton();
        jrbSeptiembre = new javax.swing.JRadioButton();
        jrbOctubre = new javax.swing.JRadioButton();
        jrbNoviembre = new javax.swing.JRadioButton();
        jrbDiciembre = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        panTowns = new javax.swing.JPanel();
        btnSaveCol = new javax.swing.JButton();
        lblDep = new javax.swing.JLabel();
        lblTowns = new javax.swing.JLabel();
        lblMuni = new javax.swing.JLabel();
        cmbTypeUser = new javax.swing.JComboBox<>();
        cmbTypeUser1 = new javax.swing.JComboBox<>();
        cmbTypeUser2 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHistory1 = new javax.swing.JTable();

        setBorder(null);
        setIconifiable(true);
        setToolTipText("gestor de cobors");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/cuaderno.png"))); // NOI18N

        btnSaveUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/Check-icon.png"))); // NOI18N
        btnSaveUser.setToolTipText("Guardar");

        lblColonia1.setText("Colonia ");

        txtColonia1.setToolTipText("Nonbre del Usuario del sistemal");

        btgMonths.add(jrbEnero);
        jrbEnero.setText("Enero");

        btgMonths.add(jrbFebreo);
        jrbFebreo.setText("Febreo");

        btgMonths.add(jrbMarzo);
        jrbMarzo.setText("Marzo");

        btgMonths.add(jrbAbril);
        jrbAbril.setText("Abril");

        btgMonths.add(jrbMayo);
        jrbMayo.setText("Mayo");

        btgMonths.add(jrbJunio);
        jrbJunio.setText("Junio");

        btgMonths.add(jrbJulio);
        jrbJulio.setText("Julio");

        btgMonths.add(jrbAgosto);
        jrbAgosto.setText("Agosto");

        btgMonths.add(jrbSeptiembre);
        jrbSeptiembre.setText("Septiembre");

        btgMonths.add(jrbOctubre);
        jrbOctubre.setText("Octubre");

        btgMonths.add(jrbNoviembre);
        jrbNoviembre.setText("Noviembre");

        btgMonths.add(jrbDiciembre);
        jrbDiciembre.setText("Diciembre");

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User", "Fecha", "Paginas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblHistory);

        javax.swing.GroupLayout panUserLayout = new javax.swing.GroupLayout(panUser);
        panUser.setLayout(panUserLayout);
        panUserLayout.setHorizontalGroup(
            panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUserLayout.createSequentialGroup()
                .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbEnero)
                            .addComponent(lblColonia1))
                        .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panUserLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(txtColonia1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panUserLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panUserLayout.createSequentialGroup()
                                        .addComponent(jrbFebreo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrbMarzo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrbAbril)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrbMayo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUserLayout.createSequentialGroup()
                                        .addComponent(jrbNoviembre)
                                        .addGap(25, 25, 25)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbJunio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbJulio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panUserLayout.createSequentialGroup()
                                        .addComponent(jrbAgosto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrbSeptiembre))
                                    .addGroup(panUserLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jrbDiciembre))))))
                    .addGroup(panUserLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jrbOctubre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSaveUser)
                .addGap(71, 71, 71))
        );
        panUserLayout.setVerticalGroup(
            panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbEnero)
                    .addComponent(jrbFebreo)
                    .addComponent(jrbMarzo)
                    .addComponent(jrbAbril)
                    .addComponent(jrbMayo)
                    .addComponent(jrbJunio)
                    .addComponent(jrbJulio)
                    .addComponent(jrbAgosto)
                    .addComponent(jrbSeptiembre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbOctubre)
                    .addComponent(jrbNoviembre)
                    .addComponent(jrbDiciembre))
                .addGap(21, 21, 21)
                .addGroup(panUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblColonia1)
                    .addComponent(txtColonia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveUser)
                .addContainerGap())
        );

        tpnControl.addTab("Ya pagados", panUser);

        btnSaveCol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icons/Check-icon.png"))); // NOI18N
        btnSaveCol.setToolTipText("Guardar");

        lblDep.setFont(new java.awt.Font("Purisa", 1, 10)); // NOI18N
        lblDep.setText("Departamentos");

        lblTowns.setFont(new java.awt.Font("Purisa", 1, 10)); // NOI18N
        lblTowns.setText("colonias y condominios");

        lblMuni.setFont(new java.awt.Font("Purisa", 1, 10)); // NOI18N
        lblMuni.setText("Municipios");

        cmbTypeUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbTypeUser1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbTypeUser2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblHistory1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User", "Fecha", "Paginas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblHistory1);

        javax.swing.GroupLayout panTownsLayout = new javax.swing.GroupLayout(panTowns);
        panTowns.setLayout(panTownsLayout);
        panTownsLayout.setHorizontalGroup(
            panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTownsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaveCol)
                .addGap(15, 15, 15))
            .addGroup(panTownsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(panTownsLayout.createSequentialGroup()
                        .addComponent(lblDep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMuni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTypeUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTowns)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTypeUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panTownsLayout.setVerticalGroup(
            panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTownsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTowns, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMuni, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbTypeUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbTypeUser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTownsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDep, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSaveCol)
                .addGap(16, 16, 16))
        );

        tpnControl.addTab("ejecutar pagos", panTowns);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tpnControl, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpnControl, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgMonths;
    private javax.swing.JButton btnSaveCol;
    private javax.swing.JButton btnSaveUser;
    public javax.swing.JComboBox<String> cmbTypeUser;
    public javax.swing.JComboBox<String> cmbTypeUser1;
    public javax.swing.JComboBox<String> cmbTypeUser2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton jrbAbril;
    private javax.swing.JRadioButton jrbAgosto;
    private javax.swing.JRadioButton jrbDiciembre;
    private javax.swing.JRadioButton jrbEnero;
    private javax.swing.JRadioButton jrbFebreo;
    private javax.swing.JRadioButton jrbJulio;
    private javax.swing.JRadioButton jrbJunio;
    private javax.swing.JRadioButton jrbMarzo;
    private javax.swing.JRadioButton jrbMayo;
    private javax.swing.JRadioButton jrbNoviembre;
    private javax.swing.JRadioButton jrbOctubre;
    private javax.swing.JRadioButton jrbSeptiembre;
    private javax.swing.JLabel lblColonia1;
    private javax.swing.JLabel lblDep;
    private javax.swing.JLabel lblMuni;
    private javax.swing.JLabel lblTowns;
    private javax.swing.JPanel panTowns;
    private javax.swing.JPanel panUser;
    public javax.swing.JTable tblHistory;
    public javax.swing.JTable tblHistory1;
    private javax.swing.JTabbedPane tpnControl;
    private javax.swing.JTextField txtColonia1;
    // End of variables declaration//GEN-END:variables
}
